### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JeannineBorn** [JonathanJustavino/quic-benchmark#19]
- [x] Future Work
  - [x] Simulate packet loss with tc
  - [x] Reuse connection (assumption: lower impact of quic socket close)
  - [x] HTTP3
  - [ ] Delay with 100ms because Close Socket went down for 50ms delay
  - [x] If Quic is moved to kernel space -> better comparison to tcp
- [x] Description for Topology (limitations LAN/WLAN)
- [x] Quic version(27) description & compare to current version draft(33)
- [x] Graph Descriptions
  - [x] RTT avg and dev
- [ ] Standard Deviations for timestamps
- [x] Table of contents

**Comment by Amyy** [comment]
- [x] Insert Topology for LOCAL measurement (currently: only topology for remote measurements)
- [x] Check used nodejs version - is it 15.0.6 or 16.05 ? We used both mixed in the README

**Comment by Amyy** [comment]
[] Insert Topology for LOCAL measurement (currently: only topology for remote measurements)

**Comment by Amyy** [comment]
- [x] explain in bytes/overhead comparion that it's only on the example of one pcap file (and reference the according one)

**Comment by Amyy** [comment]
There is a new issue with updated ToDos for the documentation
