### ISSUE TITLE
Non-Technical: Would you please share your author information with me so I can cite it.

### ISSUE THREAD

**Issue by aoki-n1** [JonathanJustavino/quic-benchmark#34]
I am a master's student.
The communication characterisation of QUIC over wireless LAN is the subject of my thesis research.

I was interested in the evaluation results of TLS/TCP and QUIC for multiple delay conditions. 
Then, I would like to cite the following URL, especially during the oral presentation of my Master's thesis.
https://github.com/JonathanJustavino/quic-benchmark#adding-delay

If it has been published as a research paper, I would like to cite it, but I could not find it.
So I'm considering citing the web page within 'quic-benchmark'.

**However, there is one problem with the author information: all three authors are known only by their GitHub usernames.
So, if possible, we would like to know the authors names(e.g. the author-element of the BibTeX)**

Best regards,

**Comment by Amyy** [comment]
Hello! Unfortunetaly we didn't publish this work as a paper, but you should be able to cite it now. See also: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files 
Best regards!

**Comment by aoki-n1** [comment]
Hello! 
Thank you great for providing exactly the source of information I was looking for.
Best regards,

**Comment by aoki-n1** [comment]
Although this is a digression from the issue, I would like to ask you one question about the evaluation environment, specifically "WLAN".

As far as I can guess, I expect that Wi-Fi(e.g. 802.11 series) and LTE or tethering(or personal hotspot) are the technologies that made up the WLAN.
If it is the 802.11 series, it would be better if there is a record of standards such as 11g or 11ac.
Do you have a test-bed record of this as an evaluation environment?
We would like to know if possible a consideration you for my research discussion.
